apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector: # select pods to forward the requests to
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017